pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
				dir('Panthar') {
                    bat 'mvn clean compile'
                }
               
            }
        }

        stage('Run Tests') {
            steps {
				 dir('Panthar') {
                bat 'mvn test -DsuiteXmlFile=Panthar/smoke.xml'
                }
            }
        }
    }
}