pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('Panthar') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Panthar') {
                    bat 'mvn test -DsuiteXmlFile=smoke.xml'
                }
            }
        }
    }
    }